### ISSUE TITLE
I need som help with a dotenv error

### ISSUE THREAD

**Issue by wmw123** [Reinoptland/portfolio-issues#1]
**I am working on this feature**

The backend of my app. I added a few routers like GET/indoorskiplaces, and that all worked. 

**And I am trying to ...**

 Work with dotenv and made the config.json a config.js file, as done in the example.

**But ...**

I get this error:

[nodemon] starting `node .`
internal/modules/cjs/loader.js:960
  throw err;
  ^

**I've tried**

To google and the main suggestion was to deleted the node_modules and npm install again.

rm -rf node_modules
npm install

But the error is still there

**Additional context**

I shows that it cannot find the config.json module:
Error: Cannot find module '/Users/lililabouchere/Code/week-9/portfolio-project/indoor-ski-app-backend/models/../config/config.json'

It's just not clear to me how I can modify this

**Comment by Reinoptland** [comment]
@wmw123 

Try this: 

- Go to models/index.js
- Check if the config file is required as config.json 
- Change it to config.js

**Comment by wmw123** [comment]
SOLVED! 

Thanks!!
