### ISSUE TITLE
I need som help with architecture of data and components

### ISSUE THREAD

**Issue by mipes4** [Reinoptland/portfolio-issues#10]
**I am working on this feature**

As a user interested in football and Eredivisie I want to do my sport bets of the Eredivisie among frieds so we can make the matches more fun to watch and maybe win a little money.

**And I am trying to ...**

Trying to list matches and corresponding predictions. There now both in different tables, but I need to list them next to each other on the page. 

**But ...**

I can't figure out how.

**I've tried**

I've tried multiple things in the frontend of the Redux Store. I fetch matches and predictions in one action so I can get them both in the state together, but then they doesn't match automatically by fixtureId of course. Then I tried to make separate components for both lists, but I don't know how to tie them together by fixtureId afterwards.

Then I thought to include Predictions in the backend which I think is the way to go, but then I'm getting stuck because /matches now sends data to the Match table (since I fetch data from another API in the backend with that GET route) and I don't know how to include Predictions in there. Tried to make another GET route, but then the matches won't fetch the data out of the API when I fetch /matches. What to do, what to do?

**Additional context**

**Comment by Reinoptland** [comment]
Try setting up a relation between Match and Prediction: 

```
Match.hasMany(models.Prediction)
Prediction.belongsTo(models.Match) 
```

Than way you can 

```javascript
// get all matches with the predictions
Match.findByPk(req.params.matchId, {
   include: [Prediction]
})

// get all predictions for a user with the corresponding match
User.findByPk(req.params.id, {
  include: {
    model: Prediction,
    include: [Match]
  }
})
```

**Comment by Reinoptland** [comment]
@mipes4

**Comment by mipes4** [comment]
Thanks for your response!

That's what I suggested what I thought was the way to go :-) 

My problem is that I don't know where to put that piece of code because I can't have two 'sends' in one GET route. If I make two different routes the problem is that I don't know how to get the data from the API.

Or is a second route the way to go in your opinion? @Reinoptland

**Comment by Reinoptland** [comment]
Ah, you get can do two DB calls, you just have to combine them. Let's take a look 👍
