### ISSUE TITLE
I need some help with refresh token in apollo cient/server

### ISSUE THREAD

**Issue by Djimovanberlo** [Reinoptland/portfolio-issues#11]
**I am working on this feature**

I thought my auth was working well, and building a system for refresh-token would be doable, given the amount of guides and docs.

**And I am trying to ...**

Trying to build a system for refresh tokens.

**But ...**

I'm using both Apollo server and Apollo client. Examples and guides seem to only use either the client or server, supported by for example express. I need assistance in picking a good strategy and maybe some technical assistance..

**I've tried**
A token is made and fetched from the backend when logging in or signin up. This is done by a mutation with response  Player and Token.

Refreshing token through request & header doesn't seem to work, as my Apollo server doesn't take requests.
```
const server = new ApolloServer({
  typeDefs,
  resolvers,
  context: { models, pubsub },
});
```
In examples, the request is passed in the context. However, it seems context can be an Object OR Function, where passing request is used as a function. 
```
context: ({ req }) => {
 // get the user token from the headers
 const token = req.headers.authorization || '';

```
I can't find out how to (if possible) access the request from an clientside mutation.

Code I found for attempting the same for Cookies is a bit more confusion. Tried some of it https://www.apollographql.com/docs/react/networking/authentication/ (among others), but hard to pin down what goes wrong, where, why, and how to handle this on the backend.

**Comment by Reinoptland** [comment]
- Legacy redux action was logging out the user
