### ISSUE TITLE
I need som help with ...

### ISSUE THREAD

**Issue by JennaLeysens** [Reinoptland/portfolio-issues#12]
**I am working on this feature**

I am updating my recipe model (changing the datatype)

**And I am trying to ...**

change the datatype of cookingTime to ENUM

**But ...**

I am receiving this error: ERROR: syntax error at or near "15" (15 is the first ENUM value). 

**I've tried**

Things you've tried / googled

I tried using this syntax: 
cookingTime: {
        type: Sequelize.ENUM,
        values: [15, 30, 45, 60, 90, 120],
        allowNull: false,
      },
from here: 
https://stackoverflow.com/questions/45437924/drop-and-create-enum-with-sequelize-correctly.

I also tried:
    cookingTime: {
        type: Sequelize.ENUM(15, 30, 45, 60, 90, 120),
        allowNull: false,
      },

Perhaps you can't edit the model like this once it's been created? I tried changing the datatype to INTEGER and that worked though.

**Comment by JennaLeysens** [comment]
I got it to work - the values have to be string it seems?

**Comment by Reinoptland** [comment]
Nice find!
