### ISSUE TITLE
I need som help with ...

### ISSUE THREAD

**Issue by SmitnAntonyDv** [Reinoptland/portfolio-issues#13]
**I am working on this feature**

sorting my locationpost Cards by distance between user and postLocation

**And I am trying to ...**

sort the distances that I have calculated between user and postLocation

**But ...**

I need to get my info inside of an array so I can use the array method .Sort(),
I have my sorting button and function call in a higher level scope so that should not be an issue however I cannot figure out how to place all my  data inside an array -> as I placed the distance calculation inside my card (so it calculates for each individual post).

- A clear and concise description of what is not working
- You can paste the error or a screenshot as well

**I've tried**

I have tried to use a useState where I setState inside the distance calculation so that I would be able to  sort the state array - however I am getting the infinite re-render problem there.

I have tried getting my distance calculation in t he global scope, however then I get stuck with dynamically getting my distance for each post.

**Additional context**

**Comment by SmitnAntonyDv** [comment]
SOLVED!

**Comment by SmitnAntonyDv** [comment]
Ok, I broke it again 😅 I'll finish the other features for now and solve this by monday

**Comment by SmitnAntonyDv** [comment]
ok it works and renders sorted, but the code looks horrible :sweat_smile: 
- I had to use a   VAR  inside of an IF code block because of scope issues. 
- would love to have a look at it with you on monday.

Enjoy the weekend :muscle:

**Comment by Reinoptland** [comment]
👍 Let's investigate on monday

**Comment by matiasgarcia91** [comment]
Antony, lets check it out!
