### ISSUE TITLE
I need som help with ...

### ISSUE THREAD

**Issue by JenniSvensson** [Reinoptland/portfolio-issues#16]
**I am working on this feature**

where a user can filter recipes based on their diet(vegan, vegetarian, gluten free)

**And I am trying to ...**

Fetch ingredients and including the recipes. This is working.

**But ...**

My logic is not correct. For example I can get the a vegan ingredient and include the recipes but that do not mean that the recipe is vegan. So because of how my models are set up I don't think there is a way of the for me to get the right info or I am missing some information on what is possible in sequelize when you have a many to many relationship. 

**I've tried**
I have tried to google queries in sequelize and also spend a lot of hours going through the sequelize manual to see if i missed something.

**Comment by Reinoptland** [comment]
Try something like 

For vegatarian:

```javascript
Recipe.findAll({
  include: {
   model: Ingredient
   where: {
     containsMeat: false
   }
  }
})
```

For vegan 

```javascript
Recipe.findAll({
  include: {
   model: Ingredient
   where: {
         [Op.and]: [ 
      {
        containsMeat: false
      },
      {
        containsDairy: false
      } // etc with shellfish as welll
    ]
   }
  }
})
```

**Comment by Reinoptland** [comment]
I **think** that should only give you vegan things recipes, otherwise check together with Matias

**Comment by matiasgarcia91** [comment]
It looks good, try it out and let me know @JenniSvensson!

**Comment by JenniSvensson** [comment]
Nope, if i do for example vegan: {
          [Op.and]: [
            { containsMeat: false },
            { containsDairy: false },
            { containsEgg: false },
            { containsSeafood: false },
            { containsShellfish: false },
          ],
        },

It filters away the non vegan ingredient but it does not do anything about the recipes it self.

**Comment by matiasgarcia91** [comment]
Jenni, this is a many-to-many right? Try this last variation and if not we'll call:
```js
Recipe.findAll({
  include: [
    {
      model: Ingredient,
      through: { 
        where: {
          [Op.and]:[{
              containsMeat: false
         },
         {
             containsDairy: false
          }] //
      },
    },
  ]
)}
```

**Comment by JenniSvensson** [comment]
yes it is a many to many, but that did not work either. I just get an error:
original: error: column ingredients->recipeIngredients.containsMeat does not exist 
Which makes sense because it does not exist in the recipeIngredients table.

**Comment by matiasgarcia91** [comment]
lets call and check it out!
