### ISSUE TITLE
I need some help with animated fullscreen menu

### ISSUE THREAD

**Issue by AnjaHrydziushka** [Reinoptland/portfolio-issues#17]
**I am working on this feature**

I made an animated fullscreen menu following the guide in Reader. 

**And I am trying to ...**

I'm trying to make navigation in my app with this menu.

**But ...**

I can not set links to menu items (for example, clicking "Lunch" in the menu sends to /lunch). Now I have an array of strings with names of menu items and I'm mapping over it.

**I've tried**

- history.push (in this case all items transfer to the last link);
- event handler functions (just don't know how to implement them correctly)

**Comment by matiasgarcia91** [comment]
hey Anja, lets check it out!
