### ISSUE TITLE
I need som help with ... 

### ISSUE THREAD

**Issue by JennaLeysens** [Reinoptland/portfolio-issues#18]
I am working on my favourites model. 

Describe the story / feature you're working on

I am trying to make a whole instance unique e.g. a favourite is unique (userId: 1 recipeId :2) so that when a user adds a favourite that favourite can only be made once.

Describe what you are trying to do

I'm trying to add unique: true but I don't think it's possible unless it's part of a column in the model? I get a validation error in the seed file even though the seeds are unique. 

Like this: 
   {
      userId: { type: DataTypes.INTEGER, allowNull: false },
      recipeId: { type: DataTypes.INTEGER, allowNull: false },
      unique: true,
    },

Things you've tried / googled
I Googled and tried this (creating an index): https://stackoverflow.com/questions/42195348/how-to-define-unique-index-on-multiple-columns-in-sequelize/46070340#comment91596272_42199137 but that broke my database or something 😲

**Comment by matiasgarcia91** [comment]
Hey Jenna! First, have you tried directly adding (by seeds maybe) the same combination of `userId - recipeId` ? It think by default this combination is unique in sequelize. I mean without any `unique` key in the models. You shouldn't be able to do it, the seeds should throw a validation error

**Comment by JennaLeysens** [comment]
I tried that now. It doesn't throw a validation error which is weird. The reason it's an issue is because the user can add and remove favourites to their profile and they can add the same one twice.

**Comment by Reinoptland** [comment]
Hi @JennaLeysens 

You can accomplish unique records in a join table by making both `userId` and `recipeId` the primary key of the UserRecipe (that's the join table right?), and having no id on the record itself 

Like so: 

```javascript
// migration

    return queryInterface.createTable(
      'UserRecipes',
      {
        createdAt: {
          allowNull: false,
          type: Sequelize.DATE,
        },
        updatedAt: {
          allowNull: false,
          type: Sequelize.DATE,
        },
        UserId: {
          type: Sequelize.Integer,
          primaryKey: true,
          foreignKey: true, 
          references: {
            model: "users",
            key: "id",
          },
        },
       RecipeId: {
          type: Sequelize.Integer,
          primaryKey: true,
          foreignKey: true, 
          references: {
            model: "recipes",
            key: "id",
          },
        },
      }
    );
```
