### ISSUE TITLE
I need some help with rendering based on array in props

### ISSUE THREAD

**Issue by mguiking** [Reinoptland/portfolio-issues#19]
**I am working on this feature**

Mapping over playing cards in a Modal

**And I am trying to ...**

Map over playing cards in a Modal. The Array to use for this map is defined in the component, though dependent on Apollo's cache.

**But ...**

I got  a TypeError: Cannot read property 'name' of undefined. The specified line where the error occurred is right after the map function.

**I've tried**

logging "name" before the map function in the component function body
logging "name" in the map function, but it doesn't log
uncommenting the things I added after it worked

**Comment by matiasgarcia91** [comment]
Hey Max! lets check it after lunch. can you paste the code where you map and define the array?

**Comment by mguiking** [comment]
**Array definition:**   
`const { data: charCards, error: charCardsSubErr, loading: charCardsLoading } = useSubscription(CHARACTER_CARDS);
`
**The map function:**
```
function ModalMap() {
        props.charCards
            .filter(card => card.player_id === null && !card.discarded)
            .map(card => {
                return (<div
                    value={card.name}
                    id={card.name}
                    className="charCard"
                    onClick={e => handleClose(card)}
                >{card.name}</div>)
            }
            )
    }
```

**Comment by matiasgarcia91** [comment]
things to try out:
1. props.charCards, log that, are you accessing the `charCards` correctly?
2. That filter function, seems to be filtering out all cards not assigned to any player, is that correct?

**Comment by mguiking** [comment]
1. If I log it inside the Modalmap function, or even inside the .map, it doesn't even appear in the console. But the same error persists.
2.  Yes, and it should filter out nothing for now

**Comment by matiasgarcia91** [comment]
`function ModalMap(props)`, could it be that you forgot to define the props as parameters of the component?
