### ISSUE TITLE
I need som help with ...

### ISSUE THREAD

**Issue by mipes4** [Reinoptland/portfolio-issues#2]
**I am working on this feature**

As a user interested in football and Eredivisie I want to do my sport bets of the Eredivisie among frieds so we can make the matches more fun to watch and maybe win a little money.

**And I am trying to ...**

Fetch data of fixtures from API and store it to my own database.

**But ...**

I got only 322 lines of fixtures, should be a lot more. I get a bunch of errors when I run my bulkCreate. (Thought it had something to do with the database size, but that has nothing to do with it) It says "too many connections for role "myDatabase" and have a bunch the following: UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). 

**I've tried**

https://www.reddit.com/r/SQL/comments/608kbj/postgresql_too_many_connections/
I tried async await and try/catch blocks on all kinds of places. Andre helped me a little with it, but I can't figure it out.

**Additional context**

**Comment by Reinoptland** [comment]
- Turns out, we did Model.bulkCreate for each piece of data, so we ran out of connections
- The other issue: if you do bulkCreate updateOnDuplicate, we have to use an array of fields that are unique

Like this:

```javascript
Employee.bulkCreate(dataArray, 
    {
        fields:["id", "name", "address"] ,
        updateOnDuplicate: ["name"] 
    } )
```
