### ISSUE TITLE
I need some help with ...

### ISSUE THREAD

**Issue by sowjanyam27** [Reinoptland/portfolio-issues#20]
**I am working on this feature**

Uploading the images from the file system.

**And I am trying to ...**

The main logic of insertions of the images into tables and retrieving is working

**But ...**

I am facing a problem when displaying the image with src={relative path} in the front end

**I've tried**

* I ve tried using src={require(trip.trip.image)} but then i got could not find module error
	Error: Cannot find module '/home/sowji/Code/Portfolio/travel-wallet-server/routers/2020-07-06T11-35-08.333Z2048.jpg'
* Then I  found this article https://survivejs.com/webpack/loading/images/ 
	If you are using React, then you use babel-plugin-transform-react-jsx-img-import to generate the require automatically.
	Even then I couldn't display the image

**Additional context**

**Comment by Reinoptland** [comment]
@matiasgarcia91 😅

**Comment by matiasgarcia91** [comment]
I think we are missing a correct configuration of `multer` to save images to a public folder and then`
`app.use('/static', express.static(path.join(__dirname, 'public')))` a static path in express to the public folder to serve the images

**Comment by sowjanyam27** [comment]
After changing the configuration to save the files to public folder and made a static path with app.use('/static', express.static(path.join(__dirname, 'public')))` .

It is working now, in the front end instead of referring to the local path referred to the static path.
