### ISSUE TITLE
I need some help with typescript re-rendering issues

### ISSUE THREAD

**Issue by Andre2610** [Reinoptland/portfolio-issues#22]
**I am working on create a new post feature**

When user wants to create a new post, I want to get the users current location

**And I am trying to ...**
I am trying to store the latitude and longitude values in a local state

**But ...**
because trypescript makes me give a value to every localstate key, the key: value resets when rerendering

- A clear and concise description of what is not working
Not an error... working exactly as intented, which is not what I intend!
- You can paste the error or a screenshot as well

**Comment by matiasgarcia91** [comment]
lets check it out!

**Comment by matiasgarcia91** [comment]
calling setState two times!
