### ISSUE TITLE
I need som help with updating state

### ISSUE THREAD

**Issue by n-lusano** [Reinoptland/portfolio-issues#24]
**I am working on this feature**

I'm assigning correct/wrong values to individual cards

**And I am trying to ...**

See the state update

**But ...**

- it works, but one click too late. So when I click the correct button, it shows the new session in the scoredcards I'm fetching and I'm not sure why
- when I click the correct button again, then the value correctly changes

**I've tried**

I tried creating a separate `store/scoredcard` folder. I wonder whether I should've tried updating state from the `session` store

**Additional context**

It works, but it needs one extra click - which means that the last card cannot get its value. I am not sure what I'm doing wrong.

**Comment by matiasgarcia91** [comment]
lets take a look!
