### ISSUE TITLE
I need some help with adding items to 'cart' with Redux

### ISSUE THREAD

**Issue by AnjaHrydziushka** [Reinoptland/portfolio-issues#25]
**I am working on this feature**

I have a list of recipes and I want to be able to add recipes I want to cook to a separate page (same as adding products to cart in a webshop, I guess?).

**And I am trying to ...**

...set up the Redux part for that feature.

**But ...**

I'm struggling with actions.js. I don't really understand what kind of action I have to make.

**I've tried**

A bunch of things, but now I already lost a track of what I'm doing :(

**Comment by matiasgarcia91** [comment]
hey anja! did you manage to make progress? should we take a look?

**Comment by AnjaHrydziushka** [comment]
Hey! No I didn't, still can not make a reducer

**Comment by matiasgarcia91** [comment]
be right with you 😄
