### ISSUE TITLE
I need some help with react-router-prompt

### ISSUE THREAD

**Issue by willemverbuyst** [Reinoptland/portfolio-issues#26]
**I am working on this feature**

When the student does a test he/she can leave halfway, I would like to prevent this.
Or at least give a score of 0 points.

**And I am trying to ...**
I found a way to generate a prompt.

**But ...**
The student obviously can still leave by clicking 'ok'.
I would like to connect a function to this 'ok' so the result of the test will be set to zero.

**I've tried**
Googled on prompts, and custom prompt, but all of it seems to work with react-class-components.

**Additional context**

-

**Comment by matiasgarcia91** [comment]
cool use case! solved it with react-router-navigation-prompt
