### ISSUE TITLE
I need som help with selecting a Marker on google-maps-react

### ISSUE THREAD

**Issue by anpospisil** [Reinoptland/portfolio-issues#27]
**I am working on this feature**

I am working on a map interface where users can select a bike from many bikes located on the map.

**And I am trying to ...**

I am trying to select a single bike Marker using an onClick event to send a post request to "reserve" the selected bike.  

**But ...**

The onClick event does not return anything

**I've tried**

console.log'ing "hi" in the function call. 

[](https://medium.com/kirsten-werner/clickable-markers-in-a-google-maps-react-component-3e9a522e1fff)

**Comment by matiasgarcia91** [comment]
hey Andrew! are the markers you are selecting placed by you? did you try setting it up like this person does for example: https://medium.com/kirsten-werner/clickable-markers-in-a-google-maps-react-component-3e9a522e1fff ?

**Comment by anpospisil** [comment]
Hi Matias! the markers are mapped from my database. I set it up very similarly to what this person posted

![Screenshot from 2020-07-07 10-17-53](https://user-images.githubusercontent.com/44903633/86746405-5632e180-c03b-11ea-9e75-facc00d7a112.png)

**Comment by anpospisil** [comment]
Also, I am using Typescript

**Comment by matiasgarcia91** [comment]
lets check it out!
