### ISSUE TITLE
I need som help with ...

### ISSUE THREAD

**Issue by wmw123** [Reinoptland/portfolio-issues#28]
**I am working on this feature**

I've added a redux store to my next.js app, which was a little harder than I thought. 
I have one element working in the store

**And I am trying to ...**

I'm trying to add more elements to the store.

**But ...**

I tried a couple of things but it's not working or keeps on crashing and I think it's because I don't really understand how the const mapStateToProps and mapDispatchToProps work

**I've tried**

I googled and watched tutorials but it would be nice if someone can think along with me :)

**Additional context**

**Comment by matiasgarcia91** [comment]
Lets take a look after standup 😄
