### ISSUE TITLE
I need som help with sending an array of unique recipeTags when creating a recipe

### ISSUE THREAD

**Issue by JennaLeysens** [Reinoptland/portfolio-issues#29]
I am working on my add a recipe form. 

**Describe the story / feature you're working on**

The user can create recipeTags (with a recipeId and tagId) when adding a recipe.

**Describe what you are trying to do**

The recipeId is the new recipe id and the tagIds are selected using checkbox inputs (the values are ids of the existing tags from the database).

- A clear and concise description of what is not working
- You can paste the error or a screenshot as well

The recipeIds are an array of objects but the tagId is always the last selected checkbox value instead of two (or more) different values.  

**Things you've tried / googled**

I've tried changing the syntax of tagId in the form and I've googled sending multiple values from a checkbox but I can't find a solution that works. 

**Add any other context about the problem here.**

**Comment by matiasgarcia91** [comment]
Hey Jenna! When you are saving this tags while clicking on them in the front-end checkboxes, how are you keeping them? in localState? check your setter on that localState that you are actually saving an array (or object) with all the clicked checkboxes. If you can log that in the component before submitting then you should get it all the way to the backend! try it and let me know

**Comment by Reinoptland** [comment]
@matiasgarcia91 turns out tagId only had one id in the array, so we wrote some filter logic and renamed a few things
