### ISSUE TITLE
Need help with insertion of data in tables

### ISSUE THREAD

**Issue by sowjanyam27** [Reinoptland/portfolio-issues#3]
Hi,

I created a foreign key reference column in the expense table like below:

 await queryInterface.addColumn("expenses", "expensetypeId", {
      type: Sequelize.INTEGER,
      references: {
        model: "expensetypes",
        key: "id",
      },
      onUpdate: "CASCADE",
      onDelete: "SET NULL",
    });

But while insertion this column is updating with null.

**Comment by sowjanyam27** [comment]
By changing relation from expense.hasMany(models.expensetype)  to expense.belongsTo(models.expensetype) the issue resolved.

**Comment by Reinoptland** [comment]
Issue was: 

- Model had a `hasMany` relation that had to be `belongsTo`
