### ISSUE TITLE
I need some help with file upload

### ISSUE THREAD

**Issue by Andre2610** [Reinoptland/portfolio-issues#30]
**I am working on this feature**

A user can create a post and upload pictures with it

**And I am trying to ...**

Figure out the api and how to create rows in 2 tables with one db query, got it to work once but for some reason, it does not work again

**But ...**
The post row is created by the picture rows are not

**I've tried**
https://cloudinary.com/documentation/react_integration
https://cloudinary.com/documentation/image_upload_api_reference

![Screenshot from 2020-07-07 10-41-23](https://user-images.githubusercontent.com/52599698/86750785-7e700f80-c03e-11ea-9bc2-be6d5fc37d80.png)

**Comment by matiasgarcia91** [comment]
did you log your `picture` array before mapping? it might be undefined if not this should work!

**Comment by Andre2610** [comment]
Logging each picture inside the map, the url is there, but the end result is the same, not picture with the post

![Screenshot from 2020-07-07 11-18-52](https://user-images.githubusercontent.com/52599698/86757801-b0d03b80-c043-11ea-92d8-e9f050c0b537.png)

**Comment by Andre2610** [comment]
I also tried: 
const postPictures = pictures.map(async (picture) => {
      await Picture.create({
        imageUrl: Picture.imageUrl,
        postId: newPostBody.id,
      });
    });
 await Promise.all(postPictures)

but the result is the same

**Comment by matiasgarcia91** [comment]
this looks like a fun one, lets take a look!

**Comment by matiasgarcia91** [comment]
probably `image urls` were too long and did not fit as string, switching to TEXT fixed it
