### ISSUE TITLE
I need som help with filtering based on multiple options

### ISSUE THREAD

**Issue by JenniSvensson** [Reinoptland/portfolio-issues#31]
**I am working on this feature**
where the user can filter the recipes

**And I am trying to ...**

trying to filter with multiple conditions.

**But ...**

So far I have only managed to filter by one option. Probably not a hard thing to figure out how to filter with more then one but for some reason I cant think of a new approach to try so need some help discussing with someone.

**I've tried**
 google on it

**Comment by Reinoptland** [comment]
@JenniSvensson I will give you a call after lunch!
