### ISSUE TITLE
I need some help with calling a function from the backend

### ISSUE THREAD

**Issue by Djimovanberlo** [Reinoptland/portfolio-issues#32]
**I am working on this feature**

In my game, players have a number of resources. Each night at midnight, the resources are updated, according to certain variables.

**And I am trying to ...**

I wrote a working function as follows:
```
`const bigFunctionTimer = () => {
  setInterval(function () {
    const date = new Date();
    if (date.getHours() === 00 && date.getMinutes() === 00) {
      bigFunction();
     // bigFunction() calculates and updates all resources
    }
  }, 60000);
  // check current time each minute. If it's midnight, bigFunction gets called.
};`
```

**But ...**

I am wondering what's a good way to call this function from the backend. Ideally, this function runs continuously.

**I've tried**

Considered having it called when a user interacts with the backend's index.js. After some consideration I think this might be an awkward approach. Effectively the function needs to be be called only once, after which it repeatedly checks the time.

Is this making sense?

What is a good strategy for this?

**Comment by matiasgarcia91** [comment]
hey Djimo! I think your looking for `cron-jobs`, take a look at this! https://medium.com/javascript-in-plain-english/how-to-schedule-cron-jobs-in-node-js-897215e2e5d3#:~:text=A%20Cron%20is%20a%20time,a%20certain%20date%20or%20time.&text=There%20are%20various%20open%20source,a%20module%20called%20node%2Dcron.
