### ISSUE TITLE
I need som help with user stats

### ISSUE THREAD

**Issue by n-lusano** [Reinoptland/portfolio-issues#34]
I'm trying to display the user's stats as he answers the flashcards, setting them correct or wrong. I update the state and the backend, but I am unable to get a hold of the active session from the frontend.
(In other words: I can either access all the cards answered by that user (any session) or none.)
So the scoring system works, but I am unable to show anything on the frontend for it

Since the scoredCards table belongs to the session table, I can eagerly fetch all the scoredCards in a session after it finished. But when I `create` a new session (by clicking the collection's card), I cannot `include` scoredCards.

I tried
- creating an empty `scoredCards`array in the `Session.create` instance, but it doesn't show up
- creating a separate array in the state in which I could push every scored card; the empty array is there but the action does not work

**Comment by Reinoptland** [comment]
#### Displaying what we have

- [x] Look for the current data in the store
- [x] Write selector to get the data you want to display
- [x] Check if this selector works
- [x] Display the data in a component

#### Keeping the data up to date as we score

- [x] When you update a score, check if it gets updated in the DB
- [x] Return a response with the new score data
- [x] Synchronize the frontend state (update the redux store)
- [x] Check

**Comment by Reinoptland** [comment]
As a user I want to add a card to an existing collection 

Frontend

- [ ] Make a page where you can see the existing cards for a collection
- [ ] Fetch the existing cards and display them
- [ ] Make a form to add a card 
- [ ] When you click the add card button, sends a request

Backend

- [ ] POST /collections/:id/cards
- [ ] Should save to the database
- [ ] Return a response with the new card

Frontend

- [ ] Check response from the backend
- [ ] Dispatch to redux
- [ ] Handle action in redux 
- [ ] Should see the new card (check)
