### ISSUE TITLE
I need some help with ...

### ISSUE THREAD

**Issue by Andre2610** [Reinoptland/portfolio-issues#35]
**I am working on this feature**

Still struggling with file upload, cant seem to figure out this api

**And I am trying to ...**

upload an image file to the api and get its URL back to store it in the DB

**But ...**

Cant figure out how to work this api

**I've tried**

Google, API docs, a lot of trial and error..

**Comment by matiasgarcia91** [comment]
lets take a look!

**Comment by matiasgarcia91** [comment]
Giving cloudinary widget a try!
