### ISSUE TITLE
I need some help with post request error 400

### ISSUE THREAD

**Issue by anpospisil** [Reinoptland/portfolio-issues#37]
**I am working on this feature**

Allowing users to reserve a bike.

**And I am trying to ...**

I am trying to post a reservation to my database

**But ...**

- I am receiving an HTTP error code 400 and "ERROR IN AUTH MIDDLEWARE JsonWebTokenError: jwt malformed"

**I've tried**

- reviewing the "cool-story-bro-server" repo

- google'ing: ERROR IN AUTH MIDDLEWARE JsonWebTokenError: jwt malformed

**Additional context**

I am receiving an HTTP error code 400 for my signUp feature as well, but my login works.

![Screenshot from 2020-07-07 16-40-55](https://user-images.githubusercontent.com/44903633/86798332-f1927980-c070-11ea-9205-e7ce17ca3066.png)

**Comment by matiasgarcia91** [comment]
Hey @anpospisil! can you post how you are doing the axios request on the frontend?

**Comment by matiasgarcia91** [comment]
do you have the `authMiddleware` set on the signup route? (you shouldn't)

**Comment by anpospisil** [comment]
sure!
![Screenshot from 2020-07-07 16-51-11](https://user-images.githubusercontent.com/44903633/86799294-15a28a80-c072-11ea-887d-e61dee0724f3.png)

**Comment by anpospisil** [comment]
authMiddleware is not set up on the signup route

**Comment by matiasgarcia91** [comment]
hmmm seems to be fine (the axios request). lets check it out

**Comment by matiasgarcia91** [comment]
Signup route => model notNull validation on an attribute
Reservations route => token was not correctly stored in the frontend
