### ISSUE TITLE
I need some help with rendering googlemaps

### ISSUE THREAD

**Issue by Andre2610** [Reinoptland/portfolio-issues#4]
**I am working on my google maps pin feature**

Describe the story / feature you're working on

**User can see the location where the post was made**

Describe what you are trying to do

**But I cant figure out the api docs for instalation**

- A clear and concise description of what is not working
- You can paste the error or a screenshot as well

**I've tried**

Things you've tried / googled

**https://tomchentw.github.io/react-google-maps/#usage--configuration
https://github.com/allynkalda/Apartment-Listing-App/blob/master/client/src/components/MapContainer.jsx'
https://medium.com/@allynak/how-to-use-google-map-api-in-react-app-edb59f64ac9d
https://dev.to/jessicabetts/how-to-use-google-maps-api-and-react-js-26c2**

I am going nuts!

**Comment by Reinoptland** [comment]
Solution: Followed step 4 of this

https://tomchentw.github.io/react-google-maps/#usage--configuration

```javascript
import { withScriptjs, withGoogleMap, GoogleMap, Marker } from "react-google-maps"

const MyMapComponent = withScriptjs(withGoogleMap((props) =>
  <GoogleMap
    defaultZoom={8}
    defaultCenter={{ lat: -34.397, lng: 150.644 }}
  >
    {props.isMarkerShown && <Marker position={{ lat: -34.397, lng: 150.644 }} />}
  </GoogleMap>
))

<MyMapComponent
  isMarkerShown
  googleMapURL="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=geometry,drawing,places"
  loadingElement={<div style={{ height: `100%` }} />}
  containerElement={<div style={{ height: `400px` }} />}
  mapElement={<div style={{ height: `100%` }} />}
/>
```

Small tweaks:

```javascript
import { withScriptjs, withGoogleMap, GoogleMap, Marker } from "react-google-maps"

const MyMapComponent = withScriptjs(withGoogleMap((props) =>
  <GoogleMap
    defaultZoom={8}
    defaultCenter={{ lat: -34.397, lng: 150.644 }}
  >
    {props.isMarkerShown && <Marker position={{ lat: -34.397, lng: 150.644 }} />}
  </GoogleMap>
))

export default () => <MyMapComponent
  isMarkerShown
  googleMapURL="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=geometry,drawing,places"
  loadingElement={<div style={{ height: `100%` }} />}
  containerElement={<div style={{ height: `400px` }} />}
  mapElement={<div style={{ height: `100%` }} />}
/>
```

right @Andre2610 ?

**Comment by Reinoptland** [comment]
And // @ts-ignore some warnings (fix later on the polish days)
