### ISSUE TITLE
I need som help with .env file again

### ISSUE THREAD

**Issue by wmw123** [Reinoptland/portfolio-issues#5]
It's not turning grey in vscode and now it's also uploaded to github.
How can I make the setting so that it's not visible anymore?

**Comment by Reinoptland** [comment]
Take the following steps 

On you local machine

- copy what is in you .env file to word or something (so you don't lose it)
- delete your .env file on your computer
- check .gitignore to see if it contains .env
- commit that you deleted you .env file
- recreate the .env file again
- check if it is grey and check to see with `git status` that git doesn't see it 

On github

- push & pullrequest

On you local machine:

- go to developmenta and pull
- change the password of your elephantsql
- add your keys back in from word (with new database url with new password)

**Comment by Reinoptland** [comment]
@wmw123
