### ISSUE TITLE
I need som help with ...

### ISSUE THREAD

**Issue by SmitnAntonyDv** [Reinoptland/portfolio-issues#6]
**I am working on this feature**

I am working on the homepage styling.

**And I am trying to ...**

I am trying to over ride boostrap styles

**But ...**
I am currently using !imporant to make my styles over ride boostrap, however I want my button div to be centered in the middle and the boostrap style is conflicting with it because it has  Display: box -> which is automatically placing the boxes to the left.

**I've tried**

I have googled how to over ride boostrap for the past 2 hours while playing around with it. I have already found out that it has to do with specifity  of the classNames and however when I follow the suggestions of being MORE specific so my name should be more specific then boostrap -> hence have a higher specifity, its not working. 

please help :D 

**Additional context**

**Comment by Reinoptland** [comment]
- Advised to use `Container`, `Col` & `Row` components 

https://react-bootstrap.netlify.app/layout/grid/

- Advised to use spacing utilities

https://mdbootstrap.com/docs/react/utilities/spacing/
