### ISSUE TITLE
I need som help with ...

### ISSUE THREAD

**Issue by SrSombre** [Reinoptland/portfolio-issues#7]
Graphs/charts of decks

I want to see the charts/stats for each deck. (CMC, spells/creature/land)

I am not able to get a .length for the number of certain cards that are included in that deck. (Eg. the number of white cards). I am able to log the cards that meet the requirements though, I cannot turn them into a temp array, counter, or whatever. Totally lost on a stupid, stupid little thing. Google didn't help me in the past hour.

For shame.

**Comment by Reinoptland** [comment]
I'll try some querying myself, this is not that easy 😓

**Comment by matiasgarcia91** [comment]
Lets check it out Dirk!

**Comment by Reinoptland** [comment]
Did we manage this @SrSombre & @matiasgarcia91 ?

**Comment by matiasgarcia91** [comment]
we didnt get to chat yesterday, @SrSombre ping!

**Comment by matiasgarcia91** [comment]
cards are counted!
