### ISSUE TITLE
I need some help with hidding Api key in the front-end

### ISSUE THREAD

**Issue by Andre2610** [Reinoptland/portfolio-issues#8]
**I am working on the googlemaps api**

Describe the story / feature you're working on

**I am trying to pass my API key to GoogleMaps**

Describe what you are trying to do

**But I would like to set it on a .env file but it somehow gets lost in the process**

- A clear and concise description of what is not working
- You can paste the error or a screenshot as well

**I've tried**

Things you've tried / googled
https://stackoverflow.com/questions/55978596/how-to-add-the-google-maps-api-key-for-a-react-app-created-with-create-react-app
https://tomchentw.github.io/react-google-maps/
https://www.digitalocean.com/community/tutorials/how-to-integrate-the-google-maps-api-into-react-applications
**Additional context**

**Comment by Reinoptland** [comment]
@Andre2610 You cannot hide an api key in the frontend

**Comment by Reinoptland** [comment]
If you want to make it harder to find you can do the following: 

https://create-react-app.dev/docs/adding-custom-environment-variables/
