### ISSUE TITLE
I need some help with setting up a database relationship

### ISSUE THREAD

**Issue by Edmund27** [Reinoptland/portfolio-issues#9]
I am trying to set up a relationship between users, conversations and messages. 
my issue is that I only want to have private converstations between two users so 
-user has many conversations
-but conversation belongs to only two users

Is it possible to set up two belongsTo relationship between conversation and users where conversation where conversation would only contain userId1 and userId2 as foreign keys?

**Comment by Reinoptland** [comment]
- We needed to specify a `foreignKey` on both the chat and user models
